const zones = [
    {
        zone: "Europe/Andorra",
        country: "Andorra",
        city: "Andorra",
        fullName: "Andorra, Andorra",
    },
    {
        zone: "Asia/Dubai",
        country: "United Arab Emirates",
        city: "Dubai",
        fullName: "Dubai, United Arab Emirates",
    },
    {
        zone: "Asia/Kabul",
        country: "Afghanistan",
        city: "Kabul",
        fullName: "Kabul, Afghanistan",
    },
    {
        zone: "America/Port_of_Spain",
        country: "Antigua and Barbuda",
        city: "Saint John's",
        fullName: "Saint John's, Antigua and Barbuda",
    },
    {
        zone: "America/Port_of_Spain",
        country: "Anguilla",
        city: "The Valley",
        fullName: "The Valley, Anguilla",
    },
    {
        zone: "Europe/Tirane",
        country: "Albania",
        city: "Tirane",
        fullName: "Tirane, Albania",
    },
    {
        zone: "Asia/Yerevan",
        country: "Armenia",
        city: "Yerevan",
        fullName: "Yerevan, Armenia",
    },
    {
        zone: "Africa/Luanda",
        country: "Angola",
        city: "Luanda",
        fullName: "Luanda, Angola",
    },
    {
        zone: "America/Argentina/Buenos_Aires",
        country: "Argentina",
        city: "Buenos Aires",
        fullName: "Buenos Aires, Argentina",
    },
    {
        zone: "America/Argentina/Cordoba",
        country: "Argentina",
        city: "Cordoba",
        fullName: "Cordoba, Argentina",
    },
    {
        zone: "America/Argentina/Salta",
        country: "Argentina",
        city: "Salta",
        fullName: "Salta, Argentina",
    },
    {
        zone: "America/Argentina/Jujuy",
        country: "Argentina",
        city: "Jujuy",
        fullName: "Jujuy, Argentina",
    },
    {
        zone: "America/Argentina/Tucuman",
        country: "Argentina",
        city: "Tucuman",
        fullName: "Tucuman, Argentina",
    },
    {
        zone: "America/Argentina/Catamarca",
        country: "Argentina",
        city: "Catamarca",
        fullName: "Catamarca, Argentina",
    },
    {
        zone: "America/Argentina/La_Rioja",
        country: "Argentina",
        city: "La Rioja",
        fullName: "La Rioja, Argentina",
    },
    {
        zone: "America/Argentina/San_Juan",
        country: "Argentina",
        city: "San Juan",
        fullName: "San Juan, Argentina",
    },
    {
        zone: "America/Argentina/Mendoza",
        country: "Argentina",
        city: "Mendoza",
        fullName: "Mendoza, Argentina",
    },
    {
        zone: "America/Argentina/San_Luis",
        country: "Argentina",
        city: "San Luis",
        fullName: "San Luis, Argentina",
    },
    {
        zone: "America/Argentina/Rio_Gallegos",
        country: "Argentina",
        city: "Rio Gallegos",
        fullName: "Rio Gallegos, Argentina",
    },
    {
        zone: "America/Argentina/Ushuaia",
        country: "Argentina",
        city: "Ushuaia",
        fullName: "Ushuaia, Argentina",
    },
    {
        zone: "Pacific/Pago_Pago",
        country: "American Samoa",
        city: "Pago Pago",
        fullName: "Pago Pago, American Samoa",
    },
    {
        zone: "Europe/Vienna",
        country: "Austria",
        city: "Vienna",
        fullName: "Vienna, Austria",
    },
    {
        zone: "Australia/Lord_Howe",
        country: "Australia",
        city: "Lord Howe",
        fullName: "Lord Howe, Australia",
    },
    {
        zone: "Australia/Hobart",
        country: "Australia",
        city: "Hobart",
        fullName: "Hobart, Australia",
    },
    {
        zone: "Australia/Currie",
        country: "Australia",
        city: "Currie",
        fullName: "Currie, Australia",
    },
    {
        zone: "Australia/Melbourne",
        country: "Australia",
        city: "Melbourne",
        fullName: "Melbourne, Australia",
    },
    {
        zone: "Australia/Sydney",
        country: "Australia",
        city: "Sydney",
        fullName: "Sydney, Australia",
    },
    {
        zone: "Australia/Broken_Hill",
        country: "Australia",
        city: "Broken Hill",
        fullName: "Broken Hill, Australia",
    },
    {
        zone: "Australia/Brisbane",
        country: "Australia",
        city: "Brisbane",
        fullName: "Brisbane, Australia",
    },
    {
        zone: "Australia/Lindeman",
        country: "Australia",
        city: "Lindeman",
        fullName: "Lindeman, Australia",
    },
    {
        zone: "Australia/Adelaide",
        country: "Australia",
        city: "Adelaide",
        fullName: "Adelaide, Australia",
    },
    {
        zone: "Australia/Darwin",
        country: "Australia",
        city: "Darwin",
        fullName: "Darwin, Australia",
    },
    {
        zone: "Australia/Perth",
        country: "Australia",
        city: "Perth",
        fullName: "Perth, Australia",
    },
    {
        zone: "Australia/Eucla",
        country: "Australia",
        city: "Eucla",
        fullName: "Eucla, Australia",
    },
    {
        zone: "America/Aruba",
        country: "Aruba",
        city: "Aruba",
        fullName: "Aruba, Aruba",
    },
    {
        zone: "Europe/Mariehamn",
        country: "Åland Islands",
        city: "Mariehamn",
        fullName: "Mariehamn, Åland Islands",
    },
    {
        zone: "Asia/Baku",
        country: "Azerbaijan",
        city: "Baku",
        fullName: "Baku, Azerbaijan",
    },
    {
        zone: "Europe/Sarajevo",
        country: "Bosnia and Herzegovina",
        city: "Sarajevo",
        fullName: "Sarajevo, Bosnia and Herzegovina",
    },
    {
        zone: "America/Barbados",
        country: "Barbados",
        city: "Barbados",
        fullName: "Barbados, Barbados",
    },
    {
        zone: "Asia/Dhaka",
        country: "Bangladesh",
        city: "Dhaka",
        fullName: "Dhaka, Bangladesh",
    },
    {
        zone: "Europe/Brussels",
        country: "Brussels",
        city: "Brussels",
        fullName: "Brussels, Brussels",
    },
    {
        zone: "Africa/Ouagadougou",
        country: "Burkina Faso",
        city: "Ouagadougou",
        fullName: "Ouagadougou, Burkina Faso",
    },
    {
        zone: "Europe/Sofia",
        country: "Bulgaria",
        city: "Sofia",
        fullName: "Sofia, Bulgaria",
    },
    {
        zone: "Asia/Bahrain",
        country: "Bahrain",
        city: "Bahrain",
        fullName: "Bahrain, Bahrain",
    },
    {
        zone: "Africa/Bujumbura",
        country: "Burundi",
        city: "Bujumbura",
        fullName: "Bujumbura, Burundi",
    },
    {
        zone: "Africa/Porto-Novo",
        country: "Benin",
        city: "Porto-Novo",
        fullName: "Porto-Novo, Benin",
    },
    {
        zone: "America/St_Barthelemy",
        country: "Saint Barthélemy",
        city: "St Barthelemy",
        fullName: "St Barthelemy, Saint Barthélemy",
    },
    {
        zone: "Atlantic/Bermuda",
        country: "Bermuda",
        city: "Bermuda",
        fullName: "Bermuda, Bermuda",
    },
    {
        zone: "Asia/Brunei",
        country: "Brunei",
        city: "Brunei",
        fullName: "Brunei, Brunei",
    },
    {
        zone: "America/La_Paz",
        country: "Bolivia",
        city: "La Paz",
        fullName: "La Paz, Bolivia",
    },
    {
        zone: "America/Kralendijk",
        country: "Bonaire, Saint Eustatius and Saba",
        city: "Kralendijk",
        fullName: "Kralendijk, Bonaire, Saint Eustatius and Saba",
    },
    {
        zone: "America/Noronha",
        country: "Brazil",
        city: "Noronha",
        fullName: "Noronha, Brazil",
    },
    {
        zone: "America/Belem",
        country: "Brazil",
        city: "Belem",
        fullName: "Belem, Brazil",
    },
    {
        zone: "America/Fortaleza",
        country: "Brazil",
        city: "Fortaleza",
        fullName: "Fortaleza, Brazil",
    },
    {
        zone: "America/Recife",
        country: "Brazil",
        city: "Recife",
        fullName: "Recife, Brazil",
    },
    {
        zone: "America/Araguaina",
        country: "Brazil",
        city: "Araguaina",
        fullName: "Araguaina, Brazil",
    },
    {
        zone: "America/Maceio",
        country: "Brazil",
        city: "Maceio",
        fullName: "Maceio, Brazil",
    },
    {
        zone: "America/Bahia",
        country: "Brazil",
        city: "Bahia",
        fullName: "Bahia, Brazil",
    },
    {
        zone: "America/Sao_Paulo",
        country: "Brazil",
        city: "Sao Paulo",
        fullName: "Sao Paulo, Brazil",
    },
    {
        zone: "America/Campo_Grande",
        country: "Brazil",
        city: "Campo Grande",
        fullName: "Campo Grande, Brazil",
    },
    {
        zone: "America/Cuiaba",
        country: "Brazil",
        city: "Cuiaba",
        fullName: "Cuiaba, Brazil",
    },
    {
        zone: "America/Santarem",
        country: "Brazil",
        city: "Santarem",
        fullName: "Santarem, Brazil",
    },
    {
        zone: "America/Porto_Velho",
        country: "Brazil",
        city: "Porto Velho",
        fullName: "Porto Velho, Brazil",
    },
    {
        zone: "America/Boa_Vista",
        country: "Brazil",
        city: "Boa Vista",
        fullName: "Boa Vista, Brazil",
    },
    {
        zone: "America/Manaus",
        country: "Brazil",
        city: "Manaus",
        fullName: "Manaus, Brazil",
    },
    {
        zone: "America/Eirunepe",
        country: "Brazil",
        city: "Eirunepe",
        fullName: "Eirunepe, Brazil",
    },
    {
        zone: "America/Rio_Branco",
        country: "Brazil",
        city: "Rio Branco",
        fullName: "Rio Branco, Brazil",
    },
    {
        zone: "America/Nassau",
        country: "The Bahamas",
        city: "Nassau",
        fullName: "Nassau, The Bahamas",
    },
    {
        zone: "Asia/Thimphu",
        country: "Bhutan",
        city: "Thimphu",
        fullName: "Thimphu, Bhutan",
    },
    {
        zone: "Africa/Gaborone",
        country: "Botswana",
        city: "Gaborone",
        fullName: "Gaborone, Botswana",
    },
    {
        zone: "Europe/Minsk",
        country: "Belarus",
        city: "Minsk",
        fullName: "Minsk, Belarus",
    },
    {
        zone: "America/Belize",
        country: "Belize",
        city: "Belize",
        fullName: "Belize, Belize",
    },
    {
        zone: "America/St_Johns",
        country: "Canada",
        city: "St Johns",
        fullName: "St Johns, Canada",
    },
    {
        zone: "America/Halifax",
        country: "Canada",
        city: "Halifax",
        fullName: "Halifax, Canada",
    },
    {
        zone: "America/Glace_Bay",
        country: "Canada",
        city: "Glace Bay",
        fullName: "Glace Bay, Canada",
    },
    {
        zone: "America/Moncton",
        country: "Canada",
        city: "Moncton",
        fullName: "Moncton, Canada",
    },
    {
        zone: "America/Goose_Bay",
        country: "Canada",
        city: "Goose Bay",
        fullName: "Goose Bay, Canada",
    },
    {
        zone: "America/Blanc-Sablon",
        country: "Canada",
        city: "Blanc-Sablon",
        fullName: "Blanc-Sablon, Canada",
    },
    {
        zone: "America/Toronto",
        country: "Canada",
        city: "Toronto",
        fullName: "Toronto, Canada",
    },
    {
        zone: "America/Nipigon",
        country: "Canada",
        city: "Nipigon",
        fullName: "Nipigon, Canada",
    },
    {
        zone: "America/Thunder_Bay",
        country: "Canada",
        city: "Thunder Bay",
        fullName: "Thunder Bay, Canada",
    },
    {
        zone: "America/Iqaluit",
        country: "Canada",
        city: "Iqaluit",
        fullName: "Iqaluit, Canada",
    },
    {
        zone: "America/Pangnirtung",
        country: "Canada",
        city: "Pangnirtung",
        fullName: "Pangnirtung, Canada",
    },
    {
        zone: "America/Atikokan",
        country: "Canada",
        city: "Atikokan",
        fullName: "Atikokan, Canada",
    },
    {
        zone: "America/Winnipeg",
        country: "Canada",
        city: "Winnipeg",
        fullName: "Winnipeg, Canada",
    },
    {
        zone: "America/Rainy_River",
        country: "Canada",
        city: "Rainy River",
        fullName: "Rainy River, Canada",
    },
    {
        zone: "America/Resolute",
        country: "Canada",
        city: "Resolute",
        fullName: "Resolute, Canada",
    },
    {
        zone: "America/Rankin_Inlet",
        country: "Canada",
        city: "Rankin Inlet",
        fullName: "Rankin Inlet, Canada",
    },
    {
        zone: "America/Regina",
        country: "Canada",
        city: "Regina",
        fullName: "Regina, Canada",
    },
    {
        zone: "America/Swift_Current",
        country: "Canada",
        city: "Swift Current",
        fullName: "Swift Current, Canada",
    },
    {
        zone: "America/Edmonton",
        country: "Canada",
        city: "Edmonton",
        fullName: "Edmonton, Canada",
    },
    {
        zone: "America/Cambridge_Bay",
        country: "Canada",
        city: "Cambridge Bay",
        fullName: "Cambridge Bay, Canada",
    },
    {
        zone: "America/Yellowknife",
        country: "Canada",
        city: "Yellowknife",
        fullName: "Yellowknife, Canada",
    },
    {
        zone: "America/Inuvik",
        country: "Canada",
        city: "Inuvik",
        fullName: "Inuvik, Canada",
    },
    {
        zone: "America/Creston",
        country: "Canada",
        city: "Creston",
        fullName: "Creston, Canada",
    },
    {
        zone: "America/Dawson_Creek",
        country: "Canada",
        city: "Dawson Creek",
        fullName: "Dawson Creek, Canada",
    },
    {
        zone: "America/Fort_Nelson",
        country: "Canada",
        city: "Fort Nelson",
        fullName: "Fort Nelson, Canada",
    },
    {
        zone: "America/Vancouver",
        country: "Canada",
        city: "Vancouver",
        fullName: "Vancouver, Canada",
    },
    {
        zone: "America/Whitehorse",
        country: "Canada",
        city: "Whitehorse",
        fullName: "Whitehorse, Canada",
    },
    {
        zone: "America/Dawson",
        country: "Canada",
        city: "Dawson",
        fullName: "Dawson, Canada",
    },
    {
        zone: "Indian/Cocos",
        country: "Cocos (Keeling) Islands",
        city: "Cocos",
        fullName: "Cocos, Cocos (Keeling) Islands",
    },
    {
        zone: "Africa/Kinshasa",
        country: "Democratic Republic of the Congo",
        city: "Kinshasa",
        fullName: "Kinshasa, Democratic Republic of the Congo",
    },
    {
        zone: "Africa/Lubumbashi",
        country: "Democratic Republic of the Congo",
        city: "Lubumbashi",
        fullName: "Lubumbashi, Democratic Republic of the Congo",
    },
    {
        zone: "Africa/Bangui",
        country: "Central African Republic",
        city: "Bangui",
        fullName: "Bangui, Central African Republic",
    },
    {
        zone: "Africa/Brazzaville",
        country: "Republic of the Congo",
        city: "Brazzaville",
        fullName: "Brazzaville, Republic of the Congo",
    },
    {
        zone: "Europe/Zurich",
        country: "Switzerland",
        city: "Zurich",
        fullName: "Zurich, Switzerland",
    },
    {
        zone: "Africa/Abidjan",
        country: "Côte d'Ivoire",
        city: "Abidjan",
        fullName: "Abidjan, Côte d'Ivoire",
    },
    {
        zone: "Pacific/Rarotonga",
        country: "Cook Islands",
        city: "Rarotonga",
        fullName: "Rarotonga, Cook Islands",
    },
    {
        zone: "America/Santiago",
        country: "Chile",
        city: "Santiago",
        fullName: "Santiago, Chile",
    },
    {
        zone: "America/Punta_Arenas",
        country: "Chile",
        city: "Punta Arenas",
        fullName: "Punta Arenas, Chile",
    },
    {
        zone: "Pacific/Easter",
        country: "Chile",
        city: "Easter",
        fullName: "Easter, Chile",
    },
    {
        zone: "Africa/Douala",
        country: "Cameroon",
        city: "Douala",
        fullName: "Douala, Cameroon",
    },
    {
        zone: "Asia/Shanghai",
        country: "China",
        city: "Shanghai",
        fullName: "Shanghai, China",
    },
    {
        zone: "Asia/Urumqi",
        country: "China",
        city: "Urumqi",
        fullName: "Urumqi, China",
    },
    {
        zone: "America/Bogota",
        country: "Colombia",
        city: "Bogota",
        fullName: "Bogota, Colombia",
    },
    {
        zone: "America/Costa_Rica",
        country: "Costa Rica",
        city: "Costa Rica",
        fullName: "Costa Rica, Costa Rica",
    },
    {
        zone: "America/Havana",
        country: "Cuba",
        city: "Havana",
        fullName: "Havana, Cuba",
    },
    {
        zone: "Atlantic/Cape_Verde",
        country: "Cape Verde",
        city: "Cape Verde",
        fullName: "Cape Verde, Cape Verde",
    },
    {
        zone: "America/Curacao",
        country: "Curaçao",
        city: "Willemstad",
        fullName: "Willemstad, Curaçao",
    },
    {
        zone: "Indian/Christmas",
        country: "Christmas Island",
        city: "Christmas",
        fullName: "Christmas, Christmas Island",
    },
    {
        zone: "Asia/Nicosia",
        country: "Cyprus",
        city: "Nicosia",
        fullName: "Nicosia, Cyprus",
    },
    {
        zone: "Asia/Famagusta",
        country: "Cyprus",
        city: "Famagusta",
        fullName: "Famagusta, Cyprus",
    },
    {
        zone: "Europe/Prague",
        country: "Czechia",
        city: "Prague",
        fullName: "Prague, Czechia",
    },
    {
        zone: "Europe/Berlin",
        country: "Germany",
        city: "Berlin",
        fullName: "Berlin, Germany",
    },
    {
        zone: "Europe/Busingen",
        country: "Germany",
        city: "Busingen",
        fullName: "Busingen, Germany",
    },
    {
        zone: "Africa/Djibouti",
        country: "Djibouti",
        city: "Djibouti",
        fullName: "Djibouti, Djibouti",
    },
    {
        zone: "Europe/Copenhagen",
        country: "Denmark",
        city: "Copenhagen",
        fullName: "Copenhagen, Denmark",
    },
    {
        zone: "America/Dominica",
        country: "Dominica",
        city: "Dominica",
        fullName: "Dominica, Dominica",
    },
    {
        zone: "America/Santo_Domingo",
        country: "Dominican Republic",
        city: "Santo Domingo",
        fullName: "Santo Domingo, Dominican Republic",
    },
    {
        zone: "Africa/Algiers",
        country: "Algeria",
        city: "Algiers",
        fullName: "Algiers, Algeria",
    },
    {
        zone: "America/Guayaquil",
        country: "Ecuador",
        city: "Guayaquil",
        fullName: "Guayaquil, Ecuador",
    },
    {
        zone: "Pacific/Galapagos",
        country: "Ecuador",
        city: "Galapagos",
        fullName: "Galapagos, Ecuador",
    },
    {
        zone: "Europe/Tallinn",
        country: "Estonia",
        city: "Tallinn",
        fullName: "Tallinn, Estonia",
    },
    {
        zone: "Africa/Cairo",
        country: "Egypt",
        city: "Cairo",
        fullName: "Cairo, Egypt",
    },
    {
        zone: "Africa/El_Aaiun",
        country: "Western Sahara",
        city: "El Aaiun",
        fullName: "El Aaiun, Western Sahara",
    },
    {
        zone: "Africa/Asmara",
        country: "Eritrea",
        city: "Asmara",
        fullName: "Asmara, Eritrea",
    },
    {
        zone: "Europe/Madrid",
        country: "Spain",
        city: "Madrid",
        fullName: "Madrid, Spain",
    },
    {
        zone: "Africa/Ceuta",
        country: "Spain",
        city: "Ceuta",
        fullName: "Ceuta, Spain",
    },
    {
        zone: "Atlantic/Canary",
        country: "Spain",
        city: "Canary",
        fullName: "Canary, Spain",
    },
    {
        zone: "Africa/Addis_Ababa",
        country: "Ethiopia",
        city: "Addis Ababa",
        fullName: "Addis Ababa, Ethiopia",
    },
    {
        zone: "Europe/Helsinki",
        country: "Finland",
        city: "Helsinki",
        fullName: "Helsinki, Finland",
    },
    {
        zone: "Pacific/Fiji",
        country: "Fiji",
        city: "Fiji",
        fullName: "Fiji, Fiji",
    },
    {
        zone: "Atlantic/Stanley",
        country: "Falkland Islands",
        city: "Stanley",
        fullName: "Stanley, Falkland Islands",
    },
    {
        zone: "Pacific/Chuuk",
        country: "Federated States of Micronesia",
        city: "Chuuk",
        fullName: "Chuuk, Federated States of Micronesia",
    },
    {
        zone: "Pacific/Pohnpei",
        country: "Federated States of Micronesia",
        city: "Pohnpei",
        fullName: "Pohnpei, Federated States of Micronesia",
    },
    {
        zone: "Pacific/Kosrae",
        country: "Federated States of Micronesia",
        city: "Kosrae",
        fullName: "Kosrae, Federated States of Micronesia",
    },
    {
        zone: "Atlantic/Faroe",
        country: "Faroe Islands",
        city: "Faroe",
        fullName: "Faroe, Faroe Islands",
    },
    {
        zone: "Europe/Paris",
        country: "France",
        city: "Paris",
        fullName: "Paris, France",
    },
    {
        zone: "Africa/Libreville",
        country: "Gabon",
        city: "Libreville",
        fullName: "Libreville, Gabon",
    },
    {
        zone: "Europe/London",
        country: "United Kingdom",
        city: "London",
        fullName: "London, United Kingdom",
    },
    {
        zone: "America/Grenada",
        country: "Grenada",
        city: "Grenada",
        fullName: "Grenada, Grenada",
    },
    {
        zone: "Asia/Tbilisi",
        country: "Georgia",
        city: "Tbilisi",
        fullName: "Tbilisi, Georgia",
    },
    {
        zone: "America/Cayenne",
        country: "French Guiana",
        city: "Cayenne",
        fullName: "Cayenne, French Guiana",
    },
    {
        zone: "Africa/Accra",
        country: "Ghana",
        city: "Accra",
        fullName: "Accra, Ghana",
    },
    {
        zone: "Europe/Gibraltar",
        country: "Gibraltar",
        city: "Gibraltar",
        fullName: "Gibraltar, Gibraltar",
    },
    {
        zone: "America/Godthab",
        country: "Greenland",
        city: "Godthab",
        fullName: "Godthab, Greenland",
    },
    {
        zone: "America/Danmarkshavn",
        country: "Greenland",
        city: "Danmarkshavn",
        fullName: "Danmarkshavn, Greenland",
    },
    {
        zone: "America/Scoresbysund",
        country: "Greenland",
        city: "Scoresbysund",
        fullName: "Scoresbysund, Greenland",
    },
    {
        zone: "America/Thule",
        country: "Greenland",
        city: "Thule",
        fullName: "Thule, Greenland",
    },
    {
        zone: "Africa/Banjul",
        country: "The Gambia",
        city: "Banjul",
        fullName: "Banjul, The Gambia",
    },
    {
        zone: "Africa/Conakry",
        country: "Guinea",
        city: "Conakry",
        fullName: "Conakry, Guinea",
    },
    {
        zone: "America/Guadeloupe",
        country: "Guadeloupe",
        city: "Guadeloupe",
        fullName: "Guadeloupe, Guadeloupe",
    },
    {
        zone: "Africa/Malabo",
        country: "Equatorial Guinea",
        city: "Malabo",
        fullName: "Malabo, Equatorial Guinea",
    },
    {
        zone: "Europe/Athens",
        country: "Greece",
        city: "Athens",
        fullName: "Athens, Greece",
    },
    {
        zone: "Atlantic/South_Georgia",
        country: "South Georgia and the South Sandwich Islands",
        city: "South Georgia",
        fullName: "South Georgia, South Georgia and the South Sandwich Islands",
    },
    {
        zone: "America/Guatemala",
        country: "Guatemala",
        city: "Guatemala",
        fullName: "Guatemala, Guatemala",
    },
    {
        zone: "Pacific/Guam",
        country: "Guam",
        city: "Guam",
        fullName: "Guam, Guam",
    },
    {
        zone: "Africa/Bissau",
        country: "Guinea-Bissau",
        city: "Bissau",
        fullName: "Bissau, Guinea-Bissau",
    },
    {
        zone: "America/Guyana",
        country: "Guyana",
        city: "Guyana",
        fullName: "Guyana, Guyana",
    },
    {
        zone: "Asia/Hong_Kong",
        country: "Hong Kong",
        city: "Hong Kong",
        fullName: "Hong Kong, Hong Kong",
    },
    {
        zone: "America/Tegucigalpa",
        country: "Honduras",
        city: "Tegucigalpa",
        fullName: "Tegucigalpa, Honduras",
    },
    {
        zone: "Europe/Zagreb",
        country: "Croatia",
        city: "Zagreb",
        fullName: "Zagreb, Croatia",
    },
    {
        zone: "America/Port-au-Prince",
        country: "Haiti",
        city: "Port-au-Prince",
        fullName: "Port-au-Prince, Haiti",
    },
    {
        zone: "Europe/Budapest",
        country: "Hungary",
        city: "Budapest",
        fullName: "Budapest, Hungary",
    },
    {
        zone: "Asia/Jakarta",
        country: "Indonesia",
        city: "Jakarta",
        fullName: "Jakarta, Indonesia",
    },
    {
        zone: "Asia/Pontianak",
        country: "Indonesia",
        city: "Pontianak",
        fullName: "Pontianak, Indonesia",
    },
    {
        zone: "Asia/Makassar",
        country: "Indonesia",
        city: "Makassar",
        fullName: "Makassar, Indonesia",
    },
    {
        zone: "Asia/Jayapura",
        country: "Indonesia",
        city: "Jayapura",
        fullName: "Jayapura, Indonesia",
    },
    {
        zone: "Europe/Dublin",
        country: "Ireland",
        city: "Dublin",
        fullName: "Dublin, Ireland",
    },
    {
        zone: "Asia/Jerusalem",
        country: "Israel",
        city: "Jerusalem",
        fullName: "Jerusalem, Israel",
    },
    {
        zone: "Asia/Kolkata",
        country: "India",
        city: "Kolkata",
        fullName: "Kolkata, India",
    },
    {
        zone: "Indian/Chagos",
        country: "British Indian Ocean Territory",
        city: "Chagos",
        fullName: "Chagos, British Indian Ocean Territory",
    },
    {
        zone: "Asia/Baghdad",
        country: "Iraq",
        city: "Baghdad",
        fullName: "Baghdad, Iraq",
    },
    {
        zone: "Asia/Tehran",
        country: "Iran",
        city: "Tehran",
        fullName: "Tehran, Iran",
    },
    {
        zone: "Atlantic/Reykjavik",
        country: "Iceland",
        city: "Reykjavik",
        fullName: "Reykjavik, Iceland",
    },
    {
        zone: "Europe/Rome",
        country: "Italy",
        city: "Rome",
        fullName: "Rome, Italy",
    },
    {
        zone: "America/Jamaica",
        country: "Jamaica",
        city: "Jamaica",
        fullName: "Jamaica, Jamaica",
    },
    {
        zone: "Asia/Amman",
        country: "Jordan",
        city: "Amman",
        fullName: "Amman, Jordan",
    },
    {
        zone: "Asia/Tokyo",
        country: "Japan",
        city: "Tokyo",
        fullName: "Tokyo, Japan",
    },
    {
        zone: "Africa/Nairobi",
        country: "Kenya",
        city: "Nairobi",
        fullName: "Nairobi, Kenya",
    },
    {
        zone: "Asia/Bishkek",
        country: "Kyrgyzstan",
        city: "Bishkek",
        fullName: "Bishkek, Kyrgyzstan",
    },
    {
        zone: "Asia/Phnom_Penh",
        country: "Cambodia",
        city: "Phnom Penh",
        fullName: "Phnom Penh, Cambodia",
    },
    {
        zone: "Pacific/Tarawa",
        country: "Kiribati",
        city: "Tarawa",
        fullName: "Tarawa, Kiribati",
    },
    {
        zone: "Pacific/Enderbury",
        country: "Kiribati",
        city: "Enderbury",
        fullName: "Enderbury, Kiribati",
    },
    {
        zone: "Pacific/Kiritimati",
        country: "Kiribati",
        city: "Kiritimati",
        fullName: "Kiritimati, Kiribati",
    },
    {
        zone: "Indian/Comoro",
        country: "Comoros",
        city: "Comoro",
        fullName: "Comoro, Comoros",
    },
    {
        zone: "America/St_Kitts",
        country: "Saint Kitts and Nevis",
        city: "St Kitts",
        fullName: "St Kitts, Saint Kitts and Nevis",
    },
    {
        zone: "Asia/Pyongyang",
        country: "North Korea",
        city: "Pyongyang",
        fullName: "Pyongyang, North Korea",
    },
    {
        zone: "Asia/Seoul",
        country: "South Korea",
        city: "Seoul",
        fullName: "Seoul, South Korea",
    },
    {
        zone: "Asia/Kuwait",
        country: "Kuwait",
        city: "Kuwait City",
        fullName: "Kuwait City, Kuwait",
    },
    {
        zone: "America/Cayman",
        country: "Cayman Islands",
        city: "Cayman",
        fullName: "Cayman, Cayman Islands",
    },
    {
        zone: "Asia/Almaty",
        country: "Kazakhstan",
        city: "Almaty",
        fullName: "Almaty, Kazakhstan",
    },
    {
        zone: "Asia/Qyzylorda",
        country: "Kazakhstan",
        city: "Qyzylorda",
        fullName: "Qyzylorda, Kazakhstan",
    },
    {
        zone: "Asia/Qostanay",
        country: "Kazakhstan",
        city: "Qostanay",
        fullName: "Qostanay, Kazakhstan",
    },
    {
        zone: "Asia/Aqtobe",
        country: "Kazakhstan",
        city: "Aqtobe",
        fullName: "Aqtobe, Kazakhstan",
    },
    {
        zone: "Asia/Aqtau",
        country: "Kazakhstan",
        city: "Aqtau",
        fullName: "Aqtau, Kazakhstan",
    },
    {
        zone: "Asia/Atyrau",
        country: "Kazakhstan",
        city: "Atyrau",
        fullName: "Atyrau, Kazakhstan",
    },
    {
        zone: "Asia/Oral",
        country: "Kazakhstan",
        city: "Oral",
        fullName: "Oral, Kazakhstan",
    },
    {
        zone: "Asia/Vientiane",
        country: "Laos",
        city: "Vientiane",
        fullName: "Vientiane, Laos",
    },
    {
        zone: "Asia/Beirut",
        country: "Lebanon",
        city: "Beirut",
        fullName: "Beirut, Lebanon",
    },
    {
        zone: "America/St_Lucia",
        country: "Saint Lucia",
        city: "St Lucia",
        fullName: "St Lucia, Saint Lucia",
    },
    {
        zone: "Europe/Vaduz",
        country: "Liechtenstein",
        city: "Vaduz",
        fullName: "Vaduz, Liechtenstein",
    },
    {
        zone: "Asia/Colombo",
        country: "Sri Lanka",
        city: "Colombo",
        fullName: "Colombo, Sri Lanka",
    },
    {
        zone: "Africa/Monrovia",
        country: "Liberia",
        city: "Monrovia",
        fullName: "Monrovia, Liberia",
    },
    {
        zone: "Africa/Maseru",
        country: "Lesotho",
        city: "Maseru",
        fullName: "Maseru, Lesotho",
    },
    {
        zone: "Europe/Vilnius",
        country: "Lithuania",
        city: "Vilnius",
        fullName: "Vilnius, Lithuania",
    },
    {
        zone: "Europe/Luxembourg",
        country: "Luxembourg",
        city: "Luxembourg",
        fullName: "Luxembourg, Luxembourg",
    },
    {
        zone: "Europe/Riga",
        country: "Latvia",
        city: "Riga",
        fullName: "Riga, Latvia",
    },
    {
        zone: "Africa/Tripoli",
        country: "Libya",
        city: "Tripoli",
        fullName: "Tripoli, Libya",
    },
    {
        zone: "Africa/Casablanca",
        country: "Morocco",
        city: "Casablanca",
        fullName: "Casablanca, Morocco",
    },
    {
        zone: "Europe/Monaco",
        country: "Monaco",
        city: "Monaco",
        fullName: "Monaco, Monaco",
    },
    {
        zone: "Europe/Chisinau",
        country: "Moldova",
        city: "Chisinau",
        fullName: "Chisinau, Moldova",
    },
    {
        zone: "Europe/Podgorica",
        country: "Montenegro",
        city: "Podgorica",
        fullName: "Podgorica, Montenegro",
    },
    {
        zone: "America/Marigot",
        country: "Saint Martin",
        city: "Marigot",
        fullName: "Marigot, Saint Martin",
    },
    {
        zone: "Indian/Antananarivo",
        country: "Madagascar",
        city: "Antananarivo",
        fullName: "Antananarivo, Madagascar",
    },
    {
        zone: "Pacific/Majuro",
        country: "Marshall Islands",
        city: "Majuro",
        fullName: "Majuro, Marshall Islands",
    },
    {
        zone: "Pacific/Kwajalein",
        country: "Marshall Islands",
        city: "Kwajalein",
        fullName: "Kwajalein, Marshall Islands",
    },
    {
        zone: "Europe/Skopje",
        country: "North Macedonia",
        city: "Skopje",
        fullName: "Skopje, North Macedonia",
    },
    {
        zone: "Africa/Bamako",
        country: "Mali",
        city: "Bamako",
        fullName: "Bamako, Mali",
    },
    {
        zone: "Asia/Yangon",
        country: "Miyanmar",
        city: "Yangon",
        fullName: "Yangon, Miyanmar",
    },
    {
        zone: "Asia/Ulaanbaatar",
        country: "Mongolia",
        city: "Ulaanbaatar",
        fullName: "Ulaanbaatar, Mongolia",
    },
    {
        zone: "Asia/Hovd",
        country: "Mongolia",
        city: "Hovd",
        fullName: "Hovd, Mongolia",
    },
    {
        zone: "Asia/Choibalsan",
        country: "Mongolia",
        city: "Choibalsan",
        fullName: "Choibalsan, Mongolia",
    },
    {
        zone: "Asia/Macau",
        country: "Macau",
        city: "Macau",
        fullName: "Macau, Macau",
    },
    {
        zone: "Pacific/Saipan",
        country: "Northern Mariana Islands",
        city: "Saipan",
        fullName: "Saipan, Northern Mariana Islands",
    },
    {
        zone: "America/Martinique",
        country: "Martinique",
        city: "Martinique",
        fullName: "Martinique, Martinique",
    },
    {
        zone: "Africa/Nouakchott",
        country: "Mauritania",
        city: "Nouakchott",
        fullName: "Nouakchott, Mauritania",
    },
    {
        zone: "America/Montserrat",
        country: "Montserrat",
        city: "Montserrat",
        fullName: "Montserrat, Montserrat",
    },
    {
        zone: "Europe/Malta",
        country: "Malta",
        city: "Malta",
        fullName: "Malta, Malta",
    },
    {
        zone: "Indian/Mauritius",
        country: "Mauritius",
        city: "Mauritius",
        fullName: "Mauritius, Mauritius",
    },
    {
        zone: "Indian/Maldives",
        country: "Maldives",
        city: "Maldives",
        fullName: "Maldives, Maldives",
    },
    {
        zone: "Africa/Blantyre",
        country: "Malawi",
        city: "Blantyre",
        fullName: "Blantyre, Malawi",
    },
    {
        zone: "America/Mexico_City",
        country: "Mexico",
        city: "Mexico City",
        fullName: "Mexico City, Mexico",
    },
    {
        zone: "America/Cancun",
        country: "Mexico",
        city: "Cancun",
        fullName: "Cancun, Mexico",
    },
    {
        zone: "America/Merida",
        country: "Mexico",
        city: "Merida",
        fullName: "Merida, Mexico",
    },
    {
        zone: "America/Monterrey",
        country: "Mexico",
        city: "Monterrey",
        fullName: "Monterrey, Mexico",
    },
    {
        zone: "America/Matamoros",
        country: "Mexico",
        city: "Matamoros",
        fullName: "Matamoros, Mexico",
    },
    {
        zone: "America/Mazatlan",
        country: "Mexico",
        city: "Mazatlan",
        fullName: "Mazatlan, Mexico",
    },
    {
        zone: "America/Chihuahua",
        country: "Mexico",
        city: "Chihuahua",
        fullName: "Chihuahua, Mexico",
    },
    {
        zone: "America/Ojinaga",
        country: "Mexico",
        city: "Ojinaga",
        fullName: "Ojinaga, Mexico",
    },
    {
        zone: "America/Hermosillo",
        country: "Mexico",
        city: "Hermosillo",
        fullName: "Hermosillo, Mexico",
    },
    {
        zone: "America/Tijuana",
        country: "Mexico",
        city: "Tijuana",
        fullName: "Tijuana, Mexico",
    },
    {
        zone: "America/Bahia_Banderas",
        country: "Mexico",
        city: "Bahia Banderas",
        fullName: "Bahia Banderas, Mexico",
    },
    {
        zone: "Asia/Kuala_Lumpur",
        country: "Malaysia",
        city: "Kuala Lumpur",
        fullName: "Kuala Lumpur, Malaysia",
    },
    {
        zone: "Asia/Kuching",
        country: "Malaysia",
        city: "Kuching",
        fullName: "Kuching, Malaysia",
    },
    {
        zone: "Africa/Maputo",
        country: "Mozambique",
        city: "Maputo",
        fullName: "Maputo, Mozambique",
    },
    {
        zone: "Africa/Windhoek",
        country: "Namibia",
        city: "Windhoek",
        fullName: "Windhoek, Namibia",
    },
    {
        zone: "Pacific/Noumea",
        country: "New Caledonia",
        city: "Noumea",
        fullName: "Noumea, New Caledonia",
    },
    {
        zone: "Africa/Niamey",
        country: "Niger",
        city: "Niamey",
        fullName: "Niamey, Niger",
    },
    {
        zone: "Pacific/Norfolk",
        country: "Norfolk Island",
        city: "Norfolk",
        fullName: "Norfolk, Norfolk Island",
    },
    {
        zone: "Africa/Lagos",
        country: "Nigeria",
        city: "Lagos",
        fullName: "Lagos, Nigeria",
    },
    {
        zone: "America/Managua",
        country: "Nicaragua",
        city: "Managua",
        fullName: "Managua, Nicaragua",
    },
    {
        zone: "Europe/Amsterdam",
        country: "Netherlands",
        city: "Amsterdam",
        fullName: "Amsterdam, Netherlands",
    },
    {
        zone: "Europe/Oslo",
        country: "Norway",
        city: "Oslo",
        fullName: "Oslo, Norway",
    },
    {
        zone: "Asia/Kathmandu",
        country: "Nepal",
        city: "Kathmandu",
        fullName: "Kathmandu, Nepal",
    },
    {
        zone: "Pacific/Nauru",
        country: "Nauru",
        city: "Nauru",
        fullName: "Nauru, Nauru",
    },
    {
        zone: "Pacific/Niue",
        country: "Niue",
        city: "Niue",
        fullName: "Niue, Niue",
    },
    {
        zone: "Pacific/Auckland",
        country: "New Zealand",
        city: "Auckland",
        fullName: "Auckland, New Zealand",
    },
    {
        zone: "Pacific/Chatham",
        country: "New Zealand",
        city: "Chatham",
        fullName: "Chatham, New Zealand",
    },
    {
        zone: "Asia/Muscat",
        country: "Oman",
        city: "Muscat",
        fullName: "Muscat, Oman",
    },
    {
        zone: "America/Panama",
        country: "Panama",
        city: "Panama",
        fullName: "Panama, Panama",
    },
    {
        zone: "America/Lima",
        country: "Peru",
        city: "Lima",
        fullName: "Lima, Peru",
    },
    {
        zone: "Pacific/Tahiti",
        country: "French Polynesia",
        city: "Tahiti",
        fullName: "Tahiti, French Polynesia",
    },
    {
        zone: "Pacific/Marquesas",
        country: "French Polynesia",
        city: "Marquesas",
        fullName: "Marquesas, French Polynesia",
    },
    {
        zone: "Pacific/Gambier",
        country: "French Polynesia",
        city: "Gambier",
        fullName: "Gambier, French Polynesia",
    },
    {
        zone: "Pacific/Port_Moresby",
        country: "Papua New Guinea",
        city: "Port Moresby",
        fullName: "Port Moresby, Papua New Guinea",
    },
    {
        zone: "Pacific/Bougainville",
        country: "Papua New Guinea",
        city: "Bougainville",
        fullName: "Bougainville, Papua New Guinea",
    },
    {
        zone: "Asia/Manila",
        country: "Philippines",
        city: "Manila",
        fullName: "Manila, Philippines",
    },
    {
        zone: "Asia/Karachi",
        country: "Pakistan",
        city: "Karachi",
        fullName: "Karachi, Pakistan",
    },
    {
        zone: "Europe/Warsaw",
        country: "Poland",
        city: "Warsaw",
        fullName: "Warsaw, Poland",
    },
    {
        zone: "America/Miquelon",
        country: "Saint Pierre and Miquelon",
        city: "Miquelon",
        fullName: "Miquelon, Saint Pierre and Miquelon",
    },
    {
        zone: "Pacific/Pitcairn",
        country: "Pitcairn Islands",
        city: "Pitcairn",
        fullName: "Pitcairn, Pitcairn Islands",
    },
    {
        zone: "America/Puerto_Rico",
        country: "Puerto Rico",
        city: "Puerto Rico",
        fullName: "Puerto Rico, Puerto Rico",
    },
    {
        zone: "Asia/Gaza",
        country: "Palestine",
        city: "Gaza",
        fullName: "Gaza, Palestine",
    },
    {
        zone: "Asia/Hebron",
        country: "Palestine",
        city: "Hebron",
        fullName: "Hebron, Palestine",
    },
    {
        zone: "Europe/Lisbon",
        country: "Portugal",
        city: "Lisbon",
        fullName: "Lisbon, Portugal",
    },
    {
        zone: "Atlantic/Madeira",
        country: "Portugal",
        city: "Madeira",
        fullName: "Madeira, Portugal",
    },
    {
        zone: "Atlantic/Azores",
        country: "Portugal",
        city: "Azores",
        fullName: "Azores, Portugal",
    },
    {
        zone: "Pacific/Palau",
        country: "Palau",
        city: "Palau",
        fullName: "Palau, Palau",
    },
    {
        zone: "America/Asuncion",
        country: "Paraguay",
        city: "Asuncion",
        fullName: "Asuncion, Paraguay",
    },
    {
        zone: "Asia/Qatar",
        country: "Qatar",
        city: "Doha",
        fullName: "Doha, Qatar",
    },
    {
        zone: "Europe/Bucharest",
        country: "Romania",
        city: "Bucharest",
        fullName: "Bucharest, Romania",
    },
    {
        zone: "Europe/Belgrade",
        country: "Serbia",
        city: "Belgrade",
        fullName: "Belgrade, Serbia",
    },
    {
        zone: "Europe/Kaliningrad",
        country: "Rusia",
        city: "Kaliningrad",
        fullName: "Kaliningrad, Rusia",
    },
    {
        zone: "Europe/Moscow",
        country: "Rusia",
        city: "Moscow",
        fullName: "Moscow, Rusia",
    },
    {
        zone: "Europe/Kirov",
        country: "Rusia",
        city: "Kirov",
        fullName: "Kirov, Rusia",
    },
    {
        zone: "Europe/Astrakhan",
        country: "Rusia",
        city: "Astrakhan",
        fullName: "Astrakhan, Rusia",
    },
    {
        zone: "Europe/Volgograd",
        country: "Rusia",
        city: "Volgograd",
        fullName: "Volgograd, Rusia",
    },
    {
        zone: "Europe/Saratov",
        country: "Rusia",
        city: "Saratov",
        fullName: "Saratov, Rusia",
    },
    {
        zone: "Europe/Ulyanovsk",
        country: "Rusia",
        city: "Ulyanovsk",
        fullName: "Ulyanovsk, Rusia",
    },
    {
        zone: "Europe/Samara",
        country: "Rusia",
        city: "Samara",
        fullName: "Samara, Rusia",
    },
    {
        zone: "Asia/Yekaterinburg",
        country: "Rusia",
        city: "Yekaterinburg",
        fullName: "Yekaterinburg, Rusia",
    },
    {
        zone: "Asia/Omsk",
        country: "Rusia",
        city: "Omsk",
        fullName: "Omsk, Rusia",
    },
    {
        zone: "Asia/Novosibirsk",
        country: "Rusia",
        city: "Novosibirsk",
        fullName: "Novosibirsk, Rusia",
    },
    {
        zone: "Asia/Barnaul",
        country: "Rusia",
        city: "Barnaul",
        fullName: "Barnaul, Rusia",
    },
    {
        zone: "Asia/Tomsk",
        country: "Rusia",
        city: "Tomsk",
        fullName: "Tomsk, Rusia",
    },
    {
        zone: "Asia/Novokuznetsk",
        country: "Rusia",
        city: "Novokuznetsk",
        fullName: "Novokuznetsk, Rusia",
    },
    {
        zone: "Asia/Krasnoyarsk",
        country: "Rusia",
        city: "Krasnoyarsk",
        fullName: "Krasnoyarsk, Rusia",
    },
    {
        zone: "Asia/Irkutsk",
        country: "Rusia",
        city: "Irkutsk",
        fullName: "Irkutsk, Rusia",
    },
    {
        zone: "Asia/Chita",
        country: "Rusia",
        city: "Chita",
        fullName: "Chita, Rusia",
    },
    {
        zone: "Asia/Yakutsk",
        country: "Rusia",
        city: "Yakutsk",
        fullName: "Yakutsk, Rusia",
    },
    {
        zone: "Asia/Khandyga",
        country: "Rusia",
        city: "Khandyga",
        fullName: "Khandyga, Rusia",
    },
    {
        zone: "Asia/Vladivostok",
        country: "Rusia",
        city: "Vladivostok",
        fullName: "Vladivostok, Rusia",
    },
    {
        zone: "Asia/Ust-Nera",
        country: "Rusia",
        city: "Ust-Nera",
        fullName: "Ust-Nera, Rusia",
    },
    {
        zone: "Asia/Magadan",
        country: "Rusia",
        city: "Magadan",
        fullName: "Magadan, Rusia",
    },
    {
        zone: "Asia/Sakhalin",
        country: "Rusia",
        city: "Sakhalin",
        fullName: "Sakhalin, Rusia",
    },
    {
        zone: "Asia/Srednekolymsk",
        country: "Rusia",
        city: "Srednekolymsk",
        fullName: "Srednekolymsk, Rusia",
    },
    {
        zone: "Asia/Kamchatka",
        country: "Rusia",
        city: "Kamchatka",
        fullName: "Kamchatka, Rusia",
    },
    {
        zone: "Asia/Anadyr",
        country: "Rusia",
        city: "Anadyr",
        fullName: "Anadyr, Rusia",
    },
    {
        zone: "Africa/Kigali",
        country: "Rwanda",
        city: "Kigali",
        fullName: "Kigali, Rwanda",
    },
    {
        zone: "Asia/Riyadh",
        country: "Saudi Arabia",
        city: "Riyadh",
        fullName: "Riyadh, Saudi Arabia",
    },
    {
        zone: "Pacific/Guadalcanal",
        country: "Solomon Islands",
        city: "Guadalcanal",
        fullName: "Guadalcanal, Solomon Islands",
    },
    {
        zone: "Indian/Mahe",
        country: "Seychelles",
        city: "Mahe",
        fullName: "Mahe, Seychelles",
    },
    {
        zone: "Africa/Khartoum",
        country: "Sudan",
        city: "Khartoum",
        fullName: "Khartoum, Sudan",
    },
    {
        zone: "Europe/Stockholm",
        country: "Sweden",
        city: "Stockholm",
        fullName: "Stockholm, Sweden",
    },
    {
        zone: "Asia/Singapore",
        country: "Singapore",
        city: "Singapore",
        fullName: "Singapore, Singapore",
    },
    {
        zone: "Atlantic/St_Helena",
        country: "Saint Helena, Ascension and Tristan da Cunha",
        city: "St Helena",
        fullName: "St Helena, Saint Helena, Ascension and Tristan da Cunha",
    },
    {
        zone: "Europe/Ljubljana",
        country: "Slovenia",
        city: "Ljubljana",
        fullName: "Ljubljana, Slovenia",
    },
    {
        zone: "Arctic/Longyearbyen",
        country: "Svalbard and Jan Mayen",
        city: "Longyearbyen",
        fullName: "Longyearbyen, Svalbard and Jan Mayen",
    },
    {
        zone: "Europe/Bratislava",
        country: "Slovakia",
        city: "Bratislava",
        fullName: "Bratislava, Slovakia",
    },
    {
        zone: "Africa/Freetown",
        country: "Sierra Leone",
        city: "Freetown",
        fullName: "Freetown, Sierra Leone",
    },
    {
        zone: "Europe/San_Marino",
        country: "San Marino",
        city: "San Marino",
        fullName: "San Marino, San Marino",
    },
    {
        zone: "Africa/Dakar",
        country: "Senegal",
        city: "Dakar",
        fullName: "Dakar, Senegal",
    },
    {
        zone: "Africa/Mogadishu",
        country: "Somalia",
        city: "Mogadishu",
        fullName: "Mogadishu, Somalia",
    },
    {
        zone: "America/Paramaribo",
        country: "Suriname",
        city: "Paramaribo",
        fullName: "Paramaribo, Suriname",
    },
    {
        zone: "Africa/Juba",
        country: "South Sudan",
        city: "Juba",
        fullName: "Juba, South Sudan",
    },
    {
        zone: "Africa/Sao_Tome",
        country: "São Tomé and Príncipe",
        city: "Sao Tome",
        fullName: "Sao Tome, São Tomé and Príncipe",
    },
    {
        zone: "America/El_Salvador",
        country: "El Salvador",
        city: "El Salvador",
        fullName: "El Salvador, El Salvador",
    },
    {
        zone: "America/Lower_Princes",
        country: "Sint Maarten",
        city: "Lower Princes",
        fullName: "Lower Princes, Sint Maarten",
    },
    {
        zone: "Asia/Damascus",
        country: "Syria",
        city: "Damascus",
        fullName: "Damascus, Syria",
    },
    {
        zone: "Africa/Mbabane",
        country: "Eswatini",
        city: "Mbabane",
        fullName: "Mbabane, Eswatini",
    },
    {
        zone: "America/Grand_Turk",
        country: "Turks and Caicos Islands",
        city: "Grand Turk",
        fullName: "Grand Turk, Turks and Caicos Islands",
    },
    {
        zone: "Africa/Ndjamena",
        country: "Chad",
        city: "Ndjamena",
        fullName: "Ndjamena, Chad",
    },
    {
        zone: "Indian/Reunion",
        country: "French Southern Territories",
        city: "Reunion",
        fullName: "Reunion, French Southern Territories",
    },
    {
        zone: "Indian/Kerguelen",
        country: "French Southern Territories",
        city: "Kerguelen",
        fullName: "Kerguelen, French Southern Territories",
    },
    {
        zone: "Africa/Lome",
        country: "Togo",
        city: "Lome",
        fullName: "Lome, Togo",
    },
    {
        zone: "Asia/Bangkok",
        country: "Thailand",
        city: "Bangkok",
        fullName: "Bangkok, Thailand",
    },
    {
        zone: "Asia/Dushanbe",
        country: "Tajikistan",
        city: "Dushanbe",
        fullName: "Dushanbe, Tajikistan",
    },
    {
        zone: "Pacific/Fakaofo",
        country: "Tokelau",
        city: "Fakaofo",
        fullName: "Fakaofo, Tokelau",
    },
    {
        zone: "Asia/Dili",
        country: "Timor-Leste",
        city: "Dili",
        fullName: "Dili, Timor-Leste",
    },
    {
        zone: "Asia/Ashgabat",
        country: "Turkmenistan",
        city: "Ashgabat",
        fullName: "Ashgabat, Turkmenistan",
    },
    {
        zone: "Africa/Tunis",
        country: "Tunisia",
        city: "Tunis",
        fullName: "Tunis, Tunisia",
    },
    {
        zone: "Pacific/Tongatapu",
        country: "Tonga",
        city: "Tongatapu",
        fullName: "Tongatapu, Tonga",
    },
    {
        zone: "Europe/Istanbul",
        country: "Turkey",
        city: "Istanbul",
        fullName: "Istanbul, Turkey",
    },
    {
        zone: "America/Port_of_Spain",
        country: "Trinidad and Tobago",
        city: "Port of Spain",
        fullName: "Port of Spain, Trinidad and Tobago",
    },
    {
        zone: "Pacific/Funafuti",
        country: "Tuvalu",
        city: "Funafuti",
        fullName: "Funafuti, Tuvalu",
    },
    {
        zone: "Asia/Taipei",
        country: "Taiwan",
        city: "Taipei",
        fullName: "Taipei, Taiwan",
    },
    {
        zone: "Africa/Dar_es_Salaam",
        country: "Tanzania",
        city: "Dar es Salaam",
        fullName: "Dar es Salaam, Tanzania",
    },
    {
        zone: "Europe/Simferopol",
        country: "Republic of Crimea",
        city: "Simferopol",
        fullName: "Simferopol, Republic of Crimea",
    },
    {
        zone: "Europe/Kiev",
        country: "Ukraine",
        city: "Kiev",
        fullName: "Kiev, Ukraine",
    },
    {
        zone: "Europe/Uzhgorod",
        country: "Ukraine",
        city: "Uzhgorod",
        fullName: "Uzhgorod, Ukraine",
    },
    {
        zone: "Europe/Zaporozhye",
        country: "Ukraine",
        city: "Zaporozhye",
        fullName: "Zaporozhye, Ukraine",
    },
    {
        zone: "Africa/Kampala",
        country: "Uganda",
        city: "Kampala",
        fullName: "Kampala, Uganda",
    },
    {
        zone: "Pacific/Wake",
        country: "U.S. Minor Outlying Islands",
        city: "Wake",
        fullName: "Wake, U.S. Minor Outlying Islands",
    },
    {
        zone: "Pacific/Midway",
        country: "U.S. Minor Outlying Islands",
        city: "Midway",
        fullName: "Midway, U.S. Minor Outlying Islands",
    },
    {
        zone: "America/New_York",
        country: "United States",
        city: "New York",
        fullName: "New York, United States",
    },
    {
        zone: "America/Detroit",
        country: "United States",
        city: "Detroit",
        fullName: "Detroit, United States",
    },
    {
        zone: "America/Kentucky/Louisville",
        country: "United States",
        city: "Louisville",
        fullName: "Louisville, United States",
    },
    {
        zone: "America/Kentucky/Monticello",
        country: "United States",
        city: "Monticello",
        fullName: "Monticello, United States",
    },
    {
        zone: "America/Indiana/Indianapolis",
        country: "United States",
        city: "Indianapolis",
        fullName: "Indianapolis, United States",
    },
    {
        zone: "America/Indiana/Vincennes",
        country: "United States",
        city: "Vincennes",
        fullName: "Vincennes, United States",
    },
    {
        zone: "America/Indiana/Winamac",
        country: "United States",
        city: "Winamac",
        fullName: "Winamac, United States",
    },
    {
        zone: "America/Indiana/Marengo",
        country: "United States",
        city: "Marengo",
        fullName: "Marengo, United States",
    },
    {
        zone: "America/Indiana/Petersburg",
        country: "United States",
        city: "Petersburg",
        fullName: "Petersburg, United States",
    },
    {
        zone: "America/Indiana/Vevay",
        country: "United States",
        city: "Vevay",
        fullName: "Vevay, United States",
    },
    {
        zone: "America/Chicago",
        country: "United States",
        city: "Chicago",
        fullName: "Chicago, United States",
    },
    {
        zone: "America/Indiana/Tell_City",
        country: "United States",
        city: "Tell City",
        fullName: "Tell City, United States",
    },
    {
        zone: "America/Indiana/Knox",
        country: "United States",
        city: "Knox",
        fullName: "Knox, United States",
    },
    {
        zone: "America/Menominee",
        country: "United States",
        city: "Menominee",
        fullName: "Menominee, United States",
    },
    {
        zone: "America/North_Dakota/Center",
        country: "United States",
        city: "Center",
        fullName: "Center, United States",
    },
    {
        zone: "America/North_Dakota/New_Salem",
        country: "United States",
        city: "New Salem",
        fullName: "New Salem, United States",
    },
    {
        zone: "America/North_Dakota/Beulah",
        country: "United States",
        city: "Beulah",
        fullName: "Beulah, United States",
    },
    {
        zone: "America/Denver",
        country: "United States",
        city: "Denver",
        fullName: "Denver, United States",
    },
    {
        zone: "America/Boise",
        country: "United States",
        city: "Boise",
        fullName: "Boise, United States",
    },
    {
        zone: "America/Phoenix",
        country: "United States",
        city: "Phoenix",
        fullName: "Phoenix, United States",
    },
    {
        zone: "America/Los_Angeles",
        country: "United States",
        city: "Los Angeles",
        fullName: "Los Angeles, United States",
    },
    {
        zone: "America/Anchorage",
        country: "United States",
        city: "Anchorage",
        fullName: "Anchorage, United States",
    },
    {
        zone: "America/Juneau",
        country: "United States",
        city: "Juneau",
        fullName: "Juneau, United States",
    },
    {
        zone: "America/Sitka",
        country: "United States",
        city: "Sitka",
        fullName: "Sitka, United States",
    },
    {
        zone: "America/Metlakatla",
        country: "United States",
        city: "Metlakatla",
        fullName: "Metlakatla, United States",
    },
    {
        zone: "America/Yakutat",
        country: "United States",
        city: "Yakutat",
        fullName: "Yakutat, United States",
    },
    {
        zone: "America/Nome",
        country: "United States",
        city: "Nome",
        fullName: "Nome, United States",
    },
    {
        zone: "America/Adak",
        country: "United States",
        city: "Adak",
        fullName: "Adak, United States",
    },
    {
        zone: "Pacific/Honolulu",
        country: "United States",
        city: "Honolulu",
        fullName: "Honolulu, United States",
    },
    {
        zone: "America/Montevideo",
        country: "Uruguay",
        city: "Montevideo",
        fullName: "Montevideo, Uruguay",
    },
    {
        zone: "Asia/Samarkand",
        country: "Uzbekistan",
        city: "Samarkand",
        fullName: "Samarkand, Uzbekistan",
    },
    {
        zone: "Asia/Tashkent",
        country: "Uzbekistan",
        city: "Tashkent",
        fullName: "Tashkent, Uzbekistan",
    },
    {
        zone: "Europe/Vatican",
        country: "Vatican City",
        city: "Vatican",
        fullName: "Vatican, Vatican City",
    },
    {
        zone: "America/St_Vincent",
        country: "Saint Vincent and the Grenadines",
        city: "St Vincent",
        fullName: "St Vincent, Saint Vincent and the Grenadines",
    },
    {
        zone: "America/Caracas",
        country: "Venezuela",
        city: "Caracas",
        fullName: "Caracas, Venezuela",
    },
    {
        zone: "America/Tortola",
        country: "British Virgin Islands",
        city: "Tortola",
        fullName: "Tortola, British Virgin Islands",
    },
    {
        zone: "America/St_Thomas",
        country: "U.S. Virgin Islands",
        city: "St Thomas",
        fullName: "St Thomas, U.S. Virgin Islands",
    },
    {
        zone: "Asia/Ho_Chi_Minh",
        country: "Vietnam",
        city: "Ho Chi Minh",
        fullName: "Ho Chi Minh, Vietnam",
    },
    {
        zone: "Pacific/Efate",
        country: "Vanuatu",
        city: "Efate",
        fullName: "Efate, Vanuatu",
    },
    {
        zone: "Pacific/Wallis",
        country: "Wallis and Futuna",
        city: "Wallis",
        fullName: "Wallis, Wallis and Futuna",
    },
    {
        zone: "Pacific/Apia",
        country: "Samoa",
        city: "Apia",
        fullName: "Apia, Samoa",
    },
    {
        zone: "Asia/Aden",
        country: "Yemen",
        city: "Aden",
        fullName: "Aden, Yemen",
    },
    {
        zone: "Indian/Mayotte",
        country: "Mayotte",
        city: "Mayotte",
        fullName: "Mayotte, Mayotte",
    },
    {
        zone: "Africa/Johannesburg",
        country: "South Africa",
        city: "Johannesburg",
        fullName: "Johannesburg, South Africa",
    },
    {
        zone: "Africa/Lusaka",
        country: "Zambia",
        city: "Lusaka",
        fullName: "Lusaka, Zambia",
    },
    {
        zone: "Africa/Harare",
        country: "Zimbabwe",
        city: "Harare",
        fullName: "Harare, Zimbabwe",
    },
];

export default zones;
